export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const USER_DETAIL_REQUEST = 'USER_DETAILS_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';

export const LOGIN_ERROR = 'LOGIN_ERROR';